<?php
/*
Plugin Name: __templateName__
Description: Description of __templateName__ plugin.
Version: 1.0
Author: Your Name
*/

namespace __templateNameToPascalCase__;


// Include the autoload file generated by Composer
require_once plugin_dir_path(__FILE__) . 'vendor/autoload.php';

use __templateNameToPascalCase__\Views;
use __templateNameToPascalCase__\Controllers;

class __templateNameToPascalCase__
{
    private $loader;

    public function __construct()
    {
        
        // Hook to initialize the plugin when WordPress is loaded
        add_action('plugins_loaded', array($this, 'init'));
        add_action('admin_menu', 'my_custom_dashboard_page');

        register_activation_hook(__FILE__, array($this, 'activate'));
        register_deactivation_hook(__FILE__, array($this, 'deactivate'));
    }

    // Method to initialize the plugin
    public function init()
    {
        $this->loader = new Loader('dependencies.json');

        $this->loader->loadScripts('assets/js/');
        $this->loader->loadStyles('assets/css/');
        // Initialization code here
        $this->register_hooks();
        $this->register_shortcodes();
        $this->render_views();
    }

    function my_custom_dashboard_page()
    {
        // Parámetros de la página
        $page_title = 'Mi Página Personalizada';
        $menu_title = 'Mi Página';
        $capability = 'manage_options';
        $menu_slug = 'my-custom-dashboard-page';
        $function = 'my_custom_dashboard_page_content';

        // Agregar la página al menú
        add_menu_page($page_title, $menu_title, $capability, $menu_slug, $function);
    }

    function my_custom_dashboard_page_content()
    {
?>
        <div class="wrap">
            <h2>Mi Página Personalizada</h2>
            <p>Este es el contenido de mi página personalizada en el dashboard.</p>
        </div>
<?php
    }

    public function render_views()
    {
        (new Views\ExampleView())->render();
    }

    // Method to register hooks
    public function register_hooks()
    {
        // Register hooks here
    }

    // Method to register shortcodes
    public function register_shortcodes()
    {
        // Register shortcodes here
    }

    // Method to activate the plugin
    public static function activate()
    {
        // Activation code here
    }

    // Method to deactivate the plugin
    public static function deactivate()
    {
        // Deactivation code here
    }
}

// Instantiate the plugin class
new __templateNameToPascalCase__();
